gitea_urls:
  api: https://gitea.asdf.cafe/api/v1
  download: https://gitea.asdf.cafe
  skip_tls_verify: false

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: "386"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    files:
      - completions/*
    rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  groups:
  - title: 'New Features'
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 0
  - title: 'Bug fixes'
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: 'Enhancements'
    regexp: '^.*?improved(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: 'Docs'
    regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: 'CI'
    regexp: '^.*?ci(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: Others
    order: 999
