pipeline:
  build:
    image: golang
    commands:
      - go mod tidy
      - go build -o bin/haunt
    when:
      event: push

  publish:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --clean
    secrets: [ gitea_token ]
    when:
      event: tag
  publish-github:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --config .githubrelease.yaml --clean
    secrets: [ github_token ]
    when:
      event: tag

