pipeline:
  build:
    image: golang
    commands:
      - go mod tidy
      - go build -o bin/haunt
      - mkdir completions
      - ./bin/haunt completion zsh > completions/haunt_zsh
      - ./bin/haunt completion bash > completions/haunt_bash
      - ./bin/haunt completion fish > completions/haunt_fish
  publish:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    secrets: [ gitea_token ]
    when:
      event: tag
  publish-github:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --config .githubrelease.yaml
    secrets: [ gitea_token ]
    when:
      event: tag

